// Auto-generated by Supabase CLI. Do not edit manually.
// Regenerate with: npx supabase gen types typescript --local > src/lib/supabase/database.types.ts

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
